[env:esp32s3]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    adafruit/Adafruit INA219 @ ^1.2.1
    jgromes/RadioLib @ ^6.5.0
    https://github.com/LSatan/SmartRC-CC1101-Driver-Lib

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0

monitor_speed = 115200
upload_protocol = custom
upload_command = powershell -Command "scp .pio\\build\\esp32s3\\bootloader.bin .pio\\build\\esp32s3\\partitions.bin .pio\\build\\esp32s3\\firmware.bin wretzel@AHGadget.local:~/s3_uploads/"
